        !> Module for setup phase by IO procedures.
        !! @author Diego T. Volpatto
        module msetup
            
            implicit none
            
            contains

            !> Subroutine to read node data file generated by EasyMesh.
            !! @param mesh_     [in/out] a mesh structure
            !! @author  Diego Volpatto
            subroutine read_nodes(mesh_)

                use meshStruture
            
                implicit none
                
                type(mesh)          :: mesh_
                integer             :: i
                character*8         :: node

                open(unit=100, file='case1.n')
                read(100,*) mesh_%nnodes
                print*, mesh_%nnodes

                call mallocNodes(mesh_, mesh_%nnodes)

                do i=1,mesh_%nnodes
                    read(100,*) node, mesh_%x(i), mesh_%y(i), mesh_%flagnode(i)
                    print*, node, mesh_%x(i), mesh_%y(i), mesh_%flagnode(i)
                enddo

                close(100)

            endsubroutine

            !> Subroutine to read element data file generated by EasyMesh.
            !! @param mesh_     [in/out] a mesh structure
            !! @author  Diego Volpatto
            subroutine read_elems(mesh_)

                use meshStruture
            
                implicit none
                
                type(mesh)          :: mesh_
                integer             :: i
                character*8         :: elem

                open(unit=100, file='case1.e')
                read(100,*) mesh_%nelems
                print*, mesh_%nelems

                call mallocElem(mesh_, mesh_%nelems)

                do i=1,mesh_%nelems
                    read(100,*) elem, & 
                        mesh_%gnode(i,1), mesh_%gnode(i,2), mesh_%gnode(i,3), &
                        mesh_%ei(i), mesh_%ej(i), mesh_%ek(i), & 
                        mesh_%si(i), mesh_%sj(i), mesh_%sk(i), &
                        mesh_%xV(i), mesh_%yV(i), mesh_%mat(i)
                    print*, elem, & 
                        mesh_%gnode(i,1), mesh_%gnode(i,2), mesh_%gnode(i,3), &
                    mesh_%xV(i), mesh_%yV(i), mesh_%mat(i)
                enddo

                close(100)

            endsubroutine

        endmodule
